export const DEMO = {
  company: {
    name: "NORTHWIND CAPITAL LTD.",
  },
  user: {
    name: "Asha",
    role: "ADMIN",
  },
  balances: [
    {
      id: "usd",
      label: "USD Account",
      token: "USD",
      network: "SWIFT",
      number: "****8901",
      address: null,
      amount: 370431,
      change: 2.4,
    },
    {
      id: "gbp",
      label: "GBP Account",
      token: "GBP",
      network: "Faster Payments",
      number: "****2345",
      address: null,
      amount: 95876,
      change: -1.2,
    },
    {
      id: "usdc",
      label: "USDC Wallet",
      token: "USDC",
      network: "Ethereum",
      number: null,
      address: "0x1a2b...3c4d",
      amount: 9568215,
      change: 0.8,
    },
    {
      id: "usdt",
      label: "USDT Wallet",
      token: "USDT",
      network: "Tron",
      number: null,
      address: "TXyz...9876",
      amount: 1456000,
      change: 1.5,
    },
  ],
  transactions: [
    {
      id: "0x12bc...a87f",
      date: "2025-12-24",
      type: "Crypto Withdrawal",
      desc: "Crypto Withdrawal",
      amount: -25000,
      ccy: "USDC",
      dest: "External Wallet",
      status: "processing",
    },
    {
      id: "0x9a3f...b21d",
      date: "2025-11-26",
      type: "Crypto Withdrawal",
      desc: "Crypto Withdrawal",
      amount: -12000,
      ccy: "USDC",
      dest: "Cold Storage",
      status: "processing",
    },
    {
      id: "SWIFT-850K",
      date: "2025-11-26",
      type: "SWIFT USDC",
      desc: "SWIFT USDC",
      amount: 850000,
      ccy: "SGD",
      dest: "From IN",
      status: "completed",
    },
    {
      id: "0xb44e...d8f1",
      date: "2025-11-04",
      type: "Crypto Withdrawal",
      desc: "Crypto Withdrawal",
      amount: -4500,
      ccy: "USDT",
      dest: "Trading Account",
      status: "processing",
    },
    {
      id: "0x2b75...7869",
      date: "2025-10-30",
      type: "Crypto Deposit",
      desc: "Crypto Deposit",
      amount: 200000,
      ccy: "USDC",
      dest: "From Exchange",
      status: "completed",
    },
    {
      id: "USD-SGD-99",
      date: "2025-10-22",
      type: "USD → SGD",
      desc: "Currency Conversion",
      amount: -99.6,
      ccy: "SGD",
      dest: "Internal",
      status: "completed",
    },
  ],
  cards: [
    {
      id: "6114",
      last4: "6114",
      holder: "Asha Mehra",
      company: "Northwind Capital",
      type: "virtual",
      status: "active",
      purpose: "Subscriptions",
      currency: "SGD",
      limit: 5000,
      used: 1199,
      txnLimit: 2000,
    },
    {
      id: "1668",
      last4: "1668",
      holder: "John Smith",
      company: "Northwind Capital",
      type: "physical",
      status: "active",
      purpose: "Business Expenses",
      currency: "USD",
      limit: 10000,
      used: 2842,
      txnLimit: 5000,
    },
    {
      id: "5265",
      last4: "5265",
      holder: "Marketing Team",
      company: "Northwind Capital",
      type: "virtual",
      status: "active",
      purpose: "Office Supplies",
      currency: "GBP",
      limit: 3000,
      used: 520,
      txnLimit: 1000,
    },
  ],
  needsAttention: [
    {
      id: 1,
      type: "verification",
      title: "Verify 'Source of funds' to unlock outbound > $2.5M / month",
      action: "VERIFY NOW",
      priority: "high",
    },
    {
      id: 2,
      type: "approval",
      title: "2 card requests pending approval",
      action: "REVIEW",
      priority: "medium",
    },
    {
      id: 3,
      type: "kyc",
      title: "1 cardholder is pending KYC",
      action: "OPEN",
      priority: "medium",
    },
  ],
  scheduledPayments: [
    {
      id: 1,
      name: "Acme Logistics",
      type: "invoice",
      date: "Tue · May 19",
      amount: -18750,
      currency: "USD",
    },
    {
      id: 2,
      name: "Payroll batch",
      type: "payroll",
      date: "Wed · May 20",
      amount: -94200,
      currency: "GBP",
    },
    {
      id: 3,
      name: "AWS",
      type: "subscription",
      date: "Fri · May 22",
      amount: -2842,
      currency: "USD",
    },
    {
      id: 1,
      name: "Acme Logistics",
      type: "invoice",
      date: "Tue · May 19",
      amount: -18750,
      currency: "USD",
    },
    {
      id: 2,
      name: "Payroll batch",
      type: "payroll",
      date: "Wed · May 20",
      amount: -94200,
      currency: "GBP",
    },
  ],
  outboundData: [
    { date: "30 days ago", payouts: 1200, cardSpend: 800 },
    { date: "29 days ago", payouts: 1500, cardSpend: 600 },
    { date: "28 days ago", payouts: 800, cardSpend: 1200 },
    { date: "27 days ago", payouts: 2000, cardSpend: 900 },
    { date: "26 days ago", payouts: 1100, cardSpend: 1500 },
    { date: "25 days ago", payouts: 1800, cardSpend: 700 },
    { date: "24 days ago", payouts: 900, cardSpend: 1100 },
    { date: "21 days ago", payouts: 1400, cardSpend: 850 },
    { date: "14 days ago", payouts: 1600, cardSpend: 950 },
    { date: "7 days ago", payouts: 2200, cardSpend: 1300 },
    { date: "Today", payouts: 1900, cardSpend: 1000 },
  ],
};
