export interface DepositAccount {
  id: string;
  accountName: string;
  accountType: 'fiat' | 'crypto';
  number?: string; // IBAN for fiat
  network?: string;
  walletAddress?: string; // for crypto
  status: 'ACTIVE' | 'INACTIVE';
  created: string;
  balance: number;
  currency: string;
  receiverName: string;
  receiverAddress: string;
  routingNumber?: string;
  memo?: string;
  icon: string; // currency icon identifier
}

export const DEPOSIT_ACCOUNTS: DepositAccount[] = [
  {
    id: 'usd-1',
    accountName: 'USD Account',
    accountType: 'fiat',
    number: '100108059',
    network: undefined,
    walletAddress: undefined,
    status: 'ACTIVE',
    created: 'Sep 25, 2025, 10:08 AM',
    balance: 248914.5,
    currency: 'USD',
    icon: 'USD',
    receiverName: 'MET CAP BANK FBO NORTHWIND CAPITAL LTD.',
    receiverAddress: '9 E Ontario St, Chicago, IL 60611',
    routingNumber: '071026408',
    memo: '100108059',
  },
  {
    id: 'gbp-1',
    accountName: 'GBP Account',
    accountType: 'fiat',
    number: 'GB44 NWBK 6020...',
    network: undefined,
    walletAddress: undefined,
    status: 'ACTIVE',
    created: 'Sep 25, 2025, 2:21 PM',
    balance: 95876.25,
    currency: 'GBP',
    icon: 'GBP',
    receiverName: 'NORTHWIND CAPITAL LTD.',
    receiverAddress: '1 Churchill Place, London E14 5HP, UK',
    routingNumber: '60-16-13',
    memo: 'GB44NWBK60201234567890',
  },
  {
    id: 'eur-1',
    accountName: 'EUR Account',
    accountType: 'fiat',
    number: 'DE89 3704 0044...',
    network: undefined,
    walletAddress: undefined,
    status: 'ACTIVE',
    created: 'Oct 4, 2025, 9:12 AM',
    balance: 156230.8,
    currency: 'EUR',
    icon: 'EUR',
    receiverName: 'NORTHWIND CAPITAL LTD.',
    receiverAddress: 'Unter den Linden 5, 10117 Berlin, Germany',
    routingNumber: undefined,
    memo: 'DE89370400440532013000',
  },
  {
    id: 'sgd-1',
    accountName: 'SGD Account',
    accountType: 'fiat',
    number: '123-456789-001',
    network: undefined,
    walletAddress: undefined,
    status: 'ACTIVE',
    created: 'Jan 12, 2026, 8:30 AM',
    balance: 425680.0,
    currency: 'SGD',
    icon: 'SGD',
    receiverName: 'NORTHWIND CAPITAL LTD.',
    receiverAddress: '2 Marina Boulevard, Singapore 018987',
    routingNumber: '7339',
    memo: '123-456789-001',
  },
  {
    id: 'aed-1',
    accountName: 'AED Account',
    accountType: 'fiat',
    number: 'AE07 0331 234...',
    network: undefined,
    walletAddress: undefined,
    status: 'ACTIVE',
    created: 'Mar 4, 2026, 11:42 AM',
    balance: 385920.5,
    currency: 'AED',
    icon: 'AED',
    receiverName: 'NORTHWIND CAPITAL LTD.',
    receiverAddress: 'Sheikh Zayed Road, Dubai, UAE',
    routingNumber: undefined,
    memo: 'AE070331234567890123456',
  },
  {
    id: 'usdc-1',
    accountName: 'USDC Wallet',
    accountType: 'crypto',
    number: undefined,
    network: 'Ethereum',
    walletAddress: '0xf26683da...8bdf1d',
    status: 'ACTIVE',
    created: 'May 15, 2026, 3:17 PM',
    balance: 1250000.0,
    currency: 'USDC',
    icon: 'USDC',
    receiverName: 'NORTHWIND CAPITAL LTD.',
    receiverAddress: '',
    routingNumber: undefined,
    memo: undefined,
  },
  {
    id: 'usdt-1',
    accountName: 'USDT Wallet',
    accountType: 'crypto',
    number: undefined,
    network: 'Ethereum',
    walletAddress: '0xa10b9342...c7e21f',
    status: 'ACTIVE',
    created: 'May 15, 2026, 3:17 PM',
    balance: 985420.75,
    currency: 'USDT',
    icon: 'USDT',
    receiverName: 'NORTHWIND CAPITAL LTD.',
    receiverAddress: '',
    routingNumber: undefined,
    memo: undefined,
  },
  {
    id: 'eurc-1',
    accountName: 'EURC Wallet',
    accountType: 'crypto',
    number: undefined,
    network: 'Ethereum',
    walletAddress: '0x4d2890b1...112a7c',
    status: 'ACTIVE',
    created: 'Apr 18, 2026, 9:55 AM',
    balance: 542100.0,
    currency: 'EURC',
    icon: 'EURC',
    receiverName: 'NORTHWIND CAPITAL LTD.',
    receiverAddress: '',
    routingNumber: undefined,
    memo: undefined,
  },
];
